version: 2

sources:
  - name: drug_shortages
    description: Drug shortage data from OpenFDA API
    tables:
      - name: drug_shortages_staging
        description: Staging table for new drug shortage data from API
        columns:
          - name: id
            description: Unique identifier for the drug shortage
            tests:
              - not_null
          - name: generic_name
            description: Generic name of the drug
          - name: company_name
            description: Name of the company/manufacturer
          - name: presentation
            description: Drug presentation/formulation
          - name: update_type
            description: Type of update to the record
          - name: update_date
            description: Date when record was last updated
          - name: availability
            description: Availability status information
          - name: related_info
            description: Related information about the shortage
          - name: resolved_note
            description: Notes about resolution (if resolved)
          - name: reason_for_shortage
            description: Reason for the drug shortage
          - name: therapeutic_category
            description: Therapeutic category of the drug
          - name: status
            description: Current status of the shortage
          - name: change_date
            description: Date when status changed
          - name: date_discontinued
            description: Date when drug was discontinued (if applicable)
          - name: availability_status
            description: Classified availability status (available, not available, limited availability, unclear)
          - name: ndc
            description: National Drug Code
          - name: created_at
            description: Timestamp when record was inserted

      - name: drug_shortages_historical_classified
        description: Historical drug shortage data (pre-existing)
        columns:
          - name: id
            description: Unique identifier for the drug shortage
            tests:
              - not_null

